### ISSUE TITLE
Question about Prompts for GPT4V

### ISSUE THREAD

**Issue by BaiqiLi123** [TIGER-AI-Lab/VIEScore#1]
Hello, you do great work and keep me inspired！
Could you please tell me how the two prompts you show in the appendix are combined：
When using GPT4V, do you pass the "context prompts" and "rating Prompt" as a whole to the "user content" in the api, or pass the "context prompts" as the api's "system content", "rating Prompt" as api's "user content"?

**Comment by vinesmsuic** [comment]
hi,
The two prompts are concentrated as one prompt and fit into user content.

Best,
Max

**Comment by BaiqiLi123** [comment]
Thank you very much
