### ISSUE TITLE
Standalone implementation class field got changed globally

### ISSUE THREAD

**Issue by SherryXTChen** [TIGER-AI-Lab/VIEScore#3]
**Describe the bug**
In [this line](https://github.com/TIGER-AI-Lab/VIEScore/blob/df464e957e007efa88996cd45627b5e2c8058fad/viescore/__init__.py#L56), once the class field `self.SC_prompt` is changed in one `evaluate()` call, a second `evaluate()` call will get the wrong prompt since keywords ("\<prompt\>"/"\<instruction\>") have been replaced. Maybe `self.SC_prompt` should be `SC_prompt`, which is initialized at the start of `evaluate()`?

**Comment by vinesmsuic** [comment]
Hi Sherry @SherryXTChen ,

Thanks for the catch! I just fixed the code.

You may want to refer to the [https://github.com/TIGER-AI-Lab/VIEScore/tree/main/paper_implementation](https://github.com/TIGER-AI-Lab/VIEScore/tree/main/paper_implementation)
Our results are all based on the code in `paper_implementation`.

**Comment by SherryXTChen** [comment]
Thank you. I will check it out as well.
